base_data_path: "data/"
data_paths:
  GSM8K: "GSM8K/test.jsonl"
  AQUA: "AQUA/test.jsonl"
  MultiArith: "MultiArith/test.jsonl"
  ASDiv: "ASDiv/test.jsonl"
  SVAMP: "SVAMP/test.jsonl"
  p_GSM8K: "p_GSM8K/r-gsm.jsonl"
  GSM_Plus: "GSM_Plus/test.jsonl"
  GSM_IC: "GSM_IC/GSM-IC_mstep.json"
  StrategyQA: "StrategyQA/test.jsonl"
  wikimultihopQA: "wikimultihopQA/dev.json"
  commonsenseQA: "commonsenseQA/test.jsonl"
  date: "date/test.jsonl"
  spartQA: "spartQA/test.jsonl"
  sports: "sports/test.jsonl"
  reclor: "reclor/val.json"
  CLUTRR: "CLUTRR/test.jsonl"
  object_counting: "object_counting/test.json"
  navigate: "navigate/test.json"
  causal_judgement: "causal_judgement/test.json"
  logical_deduction_three_objects: "logical_deduction_three_objects/test.json"
  logical_deduction_five_objects: "logical_deduction_five_objects/test.json"
  logical_deduction_seven_objects: "logical_deduction_seven_objects/test.json"
  reasoning_about_colored_objects: "reasoning_about_colored_objects/test.json"
  last_letter_2: "last_letter/test_2_letter.json"
  last_letter_4: "last_letter/test_4_letter.json"
  coin: "coin/test.json"
  word_sorting: "word_sorting/test.json"
  tracking_shuffled_objects_seven_objects: "tracking_shuffled_objects_seven_objects/test.json"
  gpqa: "gpqa/test.json"

max_question_lengths:
  GSM8K: 336
  AQUA: 200
  MultiArith: 168
  ASDiv: 252
  SVAMP: 199
  p_GSM8K: 0
  GSM_Plus: 0
  GSM_IC: 583 # 370: 2 step
  strategyQA: 78 
  wikimultihopQA: 104
  commonsenseQA: 93
  date: 105
  spartQA: 1015
  sports: 48
  reclor: 0
  CLUTRR: 612
  object_counting: 0
  navigate: 0
  causal_judgement: 0
  logical_deduction_three_objects: 0
  logical_deduction_five_objects: 0
  logical_deduction_seven_objects: 0
  reasoning_about_colored_objects: 0
  last_letter_2: 0
  last_letter_4: 0
  coin: 0
  word_sorting: 0
  tracking_shuffled_objects_seven_objects: 0
  gpqa: 0

base_prompt_path: "prompt/"
prompts:
  da:
    GSM8K: "GSM8K/fewshot_da.txt"
    AQUA: "AQUA/fewshot_da.txt"
    MultiArith: "MultiArith/fewshot_da.txt"
    ASDiv: "ASDiv/fewshot_da.txt"
    SVAMP: "SVAMP/fewshot_da.txt"
    p_GSM8K: "GSM8K/fewshot_da.txt"
    GSM_Plus: "GSM8K/fewshot_da.txt"
    GSM_IC: "GSM8K/fewshot_da.txt"
    strategyQA: "strategyQA/fewshot_da.txt"
    wikimultihopQA: "wikimultihopQA/fewshot_da.txt"
    commonsenseQA: "commonsenseQA/fewshot_da.txt"
    date: "date/fewshot_da.txt"
    spartQA: "spartQA/fewshot_da.txt"
    sports: "sports/fewshot_da.txt"
    reclor: "reclor/fewshot_da.txt"
    CLUTRR: "CLUTRR/fewshot_da.txt"
    object_counting: "object_counting/fewshot_da.txt"
    navigate: "navigate/fewshot_da.txt"
    causal_judgement: "causal_judgement/fewshot_da.txt"
    logical_deduction_three_objects: "logical_deduction_three_objects/fewshot_da.txt"
    logical_deduction_five_objects: "logical_deduction_five_objects/fewshot_da.txt"
    logical_deduction_seven_objects: "logical_deduction_seven_objects/fewshot_da.txt"
    reasoning_about_colored_objects: "reasoning_about_colored_objects/fewshot_da.txt"
    last_letter_2: "last_letter/fewshot_da.txt"
    last_letter_4: "last_letter/fewshot_da.txt"
    coin: "coin/fewshot_da.txt"
    word_sorting: "word_sorting/fewshot_da.txt"
    tracking_shuffled_objects_seven_objects: "tracking_shuffled_objects_seven_objects/fewshot_da.txt"
    gpqa: "GSM8K/fewshot_da.txt"

  cot:
    GSM8K: "GSM8K/fewshot_cot.txt"
    AQUA: "AQUA/fewshot_cot.txt"
    MultiArith: "MultiArith/fewshot_cot.txt"
    ASDiv: "ASDiv/fewshot_cot.txt"
    SVAMP: "SVAMP/fewshot_cot.txt"
    p_GSM8K: "GSM8K/fewshot_cot.txt"
    GSM_Plus: "GSM8K/fewshot_cot.txt"
    GSM_IC: "GSM8K/fewshot_cot.txt"
    strategyQA: "strategyQA/fewshot_cot.txt"
    wikimultihopQA: "wikimultihopQA/fewshot_cot.txt"
    commonsenseQA: "commonsenseQA/fewshot_cot.txt"
    date: "date/fewshot_cot.txt"
    spartQA: "spartQA/fewshot_cot.txt"
    sports: "sports/fewshot_cot.txt"
    reclor: "reclor/fewshot_cot.txt"
    CLUTRR: "CLUTRR/fewshot_cot.txt"
    object_counting: "object_counting/fewshot_cot.txt"
    navigate: "navigate/fewshot_cot_1.txt"
    causal_judgement: "causal_judgement/fewshot_cot.txt"
    logical_deduction_three_objects: "logical_deduction_three_objects/fewshot_cot.txt"
    logical_deduction_five_objects: "logical_deduction_five_objects/fewshot_cot.txt"
    logical_deduction_seven_objects: "logical_deduction_seven_objects/fewshot_cot.txt"
    reasoning_about_colored_objects: "reasoning_about_colored_objects/fewshot_cot.txt"
    last_letter_2: "last_letter/fewshot_cot.txt"
    last_letter_4: "last_letter/fewshot_cot.txt"
    coin: "coin/fewshot_cot.txt"
    word_sorting: "word_sorting/fewshot_cot.txt"
    tracking_shuffled_objects_seven_objects: "tracking_shuffled_objects_seven_objects/fewshot_cot.txt"
    gpqa: "GSM8K/fewshot_cot.txt"
  
  grounding_cot:
    GSM8K: "GSM8K/fewshot_design_1_v4.txt"
    AQUA: "AQUA/fewshot_design_1_v4.txt"
    MultiArith: "MultiArith/fewshot_design_1_v4.txt"
    ASDiv: "ASDiv/fewshot_design_1_v4.txt"
    SVAMP: "SVAMP/fewshot_design_1_v4.txt"
    p_GSM8K: "GSM8K/fewshot_design_1_v4.txt"
    GSM_Plus: "GSM8K/fewshot_design_1_v4.txt"
    GSM_IC: "GSM8K/fewshot_design_1_v4.txt"
    strategyQA: "strategyQA/fewshot_design_1_v4.txt"
    wikimultihopQA: "wikimultihopQA/fewshot_design_1_v4.txt"
    commonsenseQA: "commonsenseQA/fewshot_design_1_v4.txt"
    date: "date/fewshot_design_1_v4.txt"
    spartQA: "spartQA/fewshot_design_1_v4.txt"
    sports: "sports/fewshot_design_1_v4.txt"
    reclor: "reclor/fewshot_design_1_v4.txt"
    CLUTRR: "CLUTRR/fewshot_design_1_v4.txt"
    object_counting: "object_counting/fewshot_design_1_v4.txt"
    navigate: "navigate/fewshot_design_1_v4.txt"
    causal_judgement: "causal_judgement/fewshot_design_1_v4.txt"
    logical_deduction_three_objects: "logical_deduction_seven_objects/fewshot_design_1_v4.txt"
    logical_deduction_five_objects: "logical_deduction_seven_objects/fewshot_design_1_v4.txt"
    logical_deduction_seven_objects: "logical_deduction_seven_objects/fewshot_design_1_v4.txt"
    reasoning_about_colored_objects: "reasoning_about_colored_objects/fewshot_design_1_v4.txt"
    last_letter_2: "last_letter/fewshot_design_1_v4.txt"
    last_letter_4: "last_letter/fewshot_design_1_v4.txt"
    coin: "coin/fewshot_design_1_v4.txt"
    word_sorting: "word_sorting/fewshot_design_1_v4.txt"
    tracking_shuffled_objects_seven_objects: "tracking_shuffled_objects_seven_objects/fewshot_design_1_v4.txt"
    gpqa: "GSM8K/fewshot_design_1_v4.txt"