data_paths:
  GSM8K: "data/GSM8K/test.jsonl"
  AQUA: "data/AQUA/test.jsonl"
  MultiArith: "data/MultiArith/test.jsonl"
  ASDiv: "data/ASDiv/test.jsonl"
  SVAMP: "data/SVAMP/test.jsonl"
  p_GSM8K: "data/p_GSM8K/r-gsm.jsonl"
  GSM_Plus: "data/GSM_Plus/test.jsonl"
  GSM_IC: "data/GSM_IC/GSM-IC_mstep.json"
  StrategyQA: "data/StrategyQA/test.jsonl"
  wikimultihopQA: "data/wikimultihopQA/dev.json"
  commonsenseQA: "data/commonsenseQA/test.jsonl"
  date: "data/date/test.jsonl"
  spartQA: "data/spartQA/test.jsonl"
  sports: "data/sports/test.jsonl"
  reclor: "data/reclor/val.json"
  CLUTRR: "data/CLUTRR/test.jsonl"
  object_counting: "data/object_counting/test.json"
  navigate: "data/navigate/test.json"
  causal_judgement: "data/causal_judgement/test.json"
  logical_deduction_three_objects: "data/logical_deduction_three_objects/test.json"
  logical_deduction_five_objects: "data/logical_deduction_five_objects/test.json"
  logical_deduction_seven_objects: "data/logical_deduction_seven_objects/test.json"
  reasoning_about_colored_objects: "data/reasoning_about_colored_objects/test.json"
  last_letter_2: "data/last_letter/test_2_letter.json"
  last_letter_4: "data/last_letter/test_4_letter.json"
  coin: "data/coin/test.json"

max_question_lengths:
  GSM8K: 336
  AQUA: 200
  MultiArith: 168
  ASDiv: 252
  SVAMP: 199
  p_GSM8K: 0
  GSM_Plus: 0
  GSM_IC: 583 # 370: 2 step
  strategyQA: 78 
  wikimultihopQA: 104
  commonsenseQA: 93
  date: 105
  spartQA: 1015
  sports: 48
  reclor: 0
  CLUTRR: 612
  object_counting: 0
  navigate: 0
  causal_judgement: 0
  logical_deduction_three_objects: 0
  logical_deduction_five_objects: 0
  logical_deduction_seven_objects: 0
  reasoning_about_colored_objects: 0
  last_letter_2: 0
  last_letter_4: 0
  coin: 0

prompts:
  da:
    GSM8K: "prompt/GSM8K/fewshot_da.txt"
    AQUA: "prompt/GSM8K/fewshot_da.txt"
    MultiArith: "prompt/GSM8K/fewshot_da.txt"
    ASDiv: "prompt/GSM8K/fewshot_da.txt"
    SVAMP: "prompt/GSM8K/fewshot_da.txt"
    p_GSM8K: "prompt/GSM8K/fewshot_da.txt"
    GSM_Plus: "prompt/GSM8K/fewshot_da.txt"
    GSM_IC: "prompt/GSM8K/fewshot_da.txt"
    strategyQA: "prompt/strategyQA/fewshot_da.txt"
    wikimultihopQA: "prompt/wikimultihopQA/fewshot_da.txt"
    commonsenseQA: "prompt/commonsenseQA/fewshot_da.txt"
    date: "prompt/date/fewshot_da.txt"
    spartQA: "prompt/spartQA/fewshot_da.txt"
    sports: "prompt/sports/fewshot_da.txt"
    reclor: "prompt/reclor/fewshot_da.txt"
    CLUTRR: "prompt/CLUTRR/fewshot_da.txt"
    object_counting: "prompt/object_counting/fewshot_da.txt"
    navigate: "prompt/navigate/fewshot_da.txt"
    causal_judgement: "prompt/causal_judgement/fewshot_da.txt"
    logical_deduction_three_objects: "prompt/logical_deduction_three_objects/fewshot_da.txt"
    logical_deduction_five_objects: "prompt/logical_deduction_five_objects/fewshot_da.txt"
    logical_deduction_seven_objects: "prompt/logical_deduction_seven_objects/fewshot_da.txt"
    reasoning_about_colored_objects: "prompt/reasoning_about_colored_objects/fewshot_da.txt"
    last_letter_2: "prompt/last_letter/fewshot_da.txt"
    last_letter_4: "prompt/last_letter/fewshot_da.txt"
    coin: "prompt/coin/fewshot_da.txt"

  cot:
    GSM8K: "prompt/GSM8K/fewshot_cot.txt"
    AQUA: "prompt/GSM8K/fewshot_cot.txt"
    MultiArith: "prompt/GSM8K/fewshot_cot.txt"
    ASDiv: "prompt/GSM8K/fewshot_cot.txt"
    SVAMP: "prompt/GSM8K/fewshot_cot.txt"
    p_GSM8K: "prompt/GSM8K/fewshot_cot.txt"
    GSM_Plus: "prompt/GSM8K/fewshot_cot.txt"
    GSM_IC: "prompt/GSM8K/fewshot_cot.txt"
    strategyQA: "prompt/strategyQA/fewshot_cot.txt"
    wikimultihopQA: "prompt/wikimultihopQA/fewshot_cot.txt"
    commonsenseQA: "prompt/commonsenseQA/fewshot_cot.txt"
    date: "prompt/date/fewshot_cot.txt"
    spartQA: "prompt/spartQA/fewshot_cot.txt"
    sports: "prompt/sports/fewshot_cot.txt"
    reclor: "prompt/reclor/fewshot_cot.txt"
    CLUTRR: "prompt/CLUTRR/fewshot_cot.txt"
    object_counting: "prompt/object_counting/fewshot_cot.txt"
    navigate: "prompt/navigate/fewshot_cot.txt"
    causal_judgement: "prompt/causal_judgement/fewshot_cot.txt"
    logical_deduction_three_objects: "prompt/logical_deduction_three_objects/fewshot_cot.txt"
    logical_deduction_five_objects: "prompt/logical_deduction_five_objects/fewshot_cot.txt"
    logical_deduction_seven_objects: "prompt/logical_deduction_seven_objects/fewshot_cot.txt"
    reasoning_about_colored_objects: "prompt/reasoning_about_colored_objects/fewshot_cot.txt"
    last_letter_2: "prompt/last_letter/fewshot_cot.txt"
    last_letter_4: "prompt/last_letter/fewshot_cot.txt"
    coin: "prompt/coin/fewshot_cot.txt"
  
  grounding_cot:
    GSM8K: "prompt/GSM8K/fewshot_design_1_v4.txt"
    AQUA: "prompt/GSM8K/fewshot_design_1_v4.txt"
    MultiArith: "prompt/GSM8K/fewshot_design_1_v4.txt"
    ASDiv: "prompt/GSM8K/fewshot_design_1_v4.txt"
    SVAMP: "prompt/GSM8K/fewshot_design_1_v4.txt"
    p_GSM8K: "prompt/GSM8K/fewshot_design_1_v4.txt"
    GSM_Plus: "prompt/GSM8K/fewshot_design_1_v4.txt"
    GSM_IC: "prompt/GSM8K/fewshot_design_1_v4.txt"
    strategyQA: "prompt/strategyQA/fewshot_design_1_v4.txt"
    wikimultihopQA: "prompt/wikimultihopQA/fewshot_design_1_v4.txt"
    commonsenseQA: "prompt/commonsenseQA/fewshot_design_1_v4.txt"
    date: "prompt/date/fewshot_design_1_v4.txt"
    spartQA: "prompt/spartQA/fewshot_design_1_v4.txt"
    sports: "prompt/sports/fewshot_design_1_v4.txt"
    reclor: "prompt/reclor/fewshot_design_1_v4.txt"
    CLUTRR: "prompt/CLUTRR/fewshot_design_1_v4.txt"
    object_counting: "prompt/object_counting/fewshot_design_1_v4.txt"
    navigate: "prompt/navigate/fewshot_design_1_v4.txt"
    causal_judgement: "prompt/causal_judgement/fewshot_design_1_v4.txt"
    logical_deduction_three_objects: "prompt/logical_deduction_seven_objects/fewshot_design_1_v4.txt"
    logical_deduction_five_objects: "prompt/logical_deduction_seven_objects/fewshot_design_1_v4.txt"
    logical_deduction_seven_objects: "prompt/logical_deduction_seven_objects/fewshot_design_1_v4.txt"
    reasoning_about_colored_objects: "prompt/reasoning_about_colored_objects/fewshot_design_1_v4.txt"
    last_letter_2: "prompt/last_letter/fewshot_design_1_v4.txt"
    last_letter_4: "prompt/last_letter/fewshot_design_1_v4.txt"
    coin: "prompt/coin/fewshot_design_1_v4.txt"